package lyricgap_;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author jprecreativo
 */
public class MainScreen extends Screen 
{
    /**
     * Creates new form MainScreen
     */
    public MainScreen() 
    {
        initComponents();
        
        super.inicialize(this.getWidth(), this.getHeight(), "LyricGap_");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_IN = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_OUT = new javax.swing.JTextArea();
        bt_MakeGaps = new javax.swing.JButton();
        bt_Clipboard = new javax.swing.JButton();
        bt_CleanFields = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta_IN.setColumns(20);
        ta_IN.setRows(5);
        jScrollPane1.setViewportView(ta_IN);

        ta_OUT.setEditable(false);
        ta_OUT.setColumns(20);
        ta_OUT.setRows(5);
        ta_OUT.setFocusable(false);
        jScrollPane2.setViewportView(ta_OUT);

        bt_MakeGaps.setText("Make gaps!");
        bt_MakeGaps.setFocusable(false);
        bt_MakeGaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MakeGapsActionPerformed(evt);
            }
        });

        bt_Clipboard.setText("Copy to clipboard");
        bt_Clipboard.setFocusable(false);
        bt_Clipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ClipboardActionPerformed(evt);
            }
        });

        bt_CleanFields.setText("Clean fields");
        bt_CleanFields.setFocusable(false);
        bt_CleanFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CleanFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(bt_MakeGaps)
                .addGap(42, 42, 42)
                .addComponent(bt_Clipboard)
                .addGap(44, 44, 44)
                .addComponent(bt_CleanFields)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_MakeGaps)
                    .addComponent(bt_Clipboard)
                    .addComponent(bt_CleanFields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CleanFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CleanFieldsActionPerformed
        
        ta_IN.setText("");
        ta_OUT.setText("");
    }//GEN-LAST:event_bt_CleanFieldsActionPerformed

    private void bt_ClipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ClipboardActionPerformed
        
        String lyricGap = ta_OUT.getText();
        StringSelection stringSelection = new StringSelection(lyricGap);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_bt_ClipboardActionPerformed

    private void bt_MakeGapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MakeGapsActionPerformed
        
        if(!"".equals(ta_IN.getText()))
        {
            GapMaker.song = ta_IN.getText();
        
            ta_OUT.setText(GapMaker.makeGaps());
        }
    }//GEN-LAST:event_bt_MakeGapsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_CleanFields;
    private javax.swing.JButton bt_Clipboard;
    private javax.swing.JButton bt_MakeGaps;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta_IN;
    private javax.swing.JTextArea ta_OUT;
    // End of variables declaration//GEN-END:variables
}
