package lyricgap_;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;

/**
 *
 * @author jprecreativo
 */
public class MainScreen extends Screen 
{
    /**
     * Creates new form MainScreen
     */
    public MainScreen() 
    {
        initComponents();
        
        super.inicialize(this.getWidth(), this.getHeight(), "LyricGap_");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_gaps = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_IN = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_OUT = new javax.swing.JTextArea();
        bt_MakeGaps = new javax.swing.JButton();
        bt_Clipboard = new javax.swing.JButton();
        bt_CleanFields = new javax.swing.JButton();
        bt_stopWords = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rb_few = new javax.swing.JRadioButton();
        rb_medium = new javax.swing.JRadioButton();
        rb_many = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta_IN.setColumns(20);
        ta_IN.setRows(5);
        jScrollPane1.setViewportView(ta_IN);

        ta_OUT.setEditable(false);
        ta_OUT.setColumns(20);
        ta_OUT.setRows(5);
        ta_OUT.setFocusable(false);
        jScrollPane2.setViewportView(ta_OUT);

        bt_MakeGaps.setText("Make gaps!");
        bt_MakeGaps.setFocusable(false);
        bt_MakeGaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_MakeGapsActionPerformed(evt);
            }
        });

        bt_Clipboard.setText("Copy to clipboard");
        bt_Clipboard.setFocusable(false);
        bt_Clipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ClipboardActionPerformed(evt);
            }
        });

        bt_CleanFields.setText("Clean fields");
        bt_CleanFields.setFocusable(false);
        bt_CleanFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CleanFieldsActionPerformed(evt);
            }
        });

        bt_stopWords.setText("Add stop words");
        bt_stopWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stopWordsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("GAPS:");

        bg_gaps.add(rb_few);
        rb_few.setText("Few");

        bg_gaps.add(rb_medium);
        rb_medium.setSelected(true);
        rb_medium.setText("Medium");

        bg_gaps.add(rb_many);
        rb_many.setText("Many");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_stopWords, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_MakeGaps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Clipboard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_CleanFields))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(rb_few)
                                .addGap(10, 10, 10)
                                .addComponent(rb_medium)
                                .addGap(10, 10, 10)
                                .addComponent(rb_many)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_MakeGaps)
                    .addComponent(bt_Clipboard)
                    .addComponent(bt_CleanFields)
                    .addComponent(bt_stopWords))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rb_few)
                    .addComponent(rb_medium)
                    .addComponent(rb_many))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CleanFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CleanFieldsActionPerformed
        
        ta_IN.setText("");
        ta_OUT.setText("");
    }//GEN-LAST:event_bt_CleanFieldsActionPerformed

    private void bt_ClipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ClipboardActionPerformed
        
        String lyricGap = ta_OUT.getText();
        StringSelection stringSelection = new StringSelection(lyricGap);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_bt_ClipboardActionPerformed

    private void bt_MakeGapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_MakeGapsActionPerformed
        
        if(!"".equals(ta_IN.getText()))
        {
            GapMaker.song = ta_IN.getText();
            
            if(rb_few.isSelected())
                GapMaker.gaps = 0.045f;
            
            else if(rb_medium.isSelected())
                GapMaker.gaps = 0.055f;
            
            else
                GapMaker.gaps = 0.065f;
        
            ta_OUT.setText(GapMaker.makeGaps());
        }
    }//GEN-LAST:event_bt_MakeGapsActionPerformed

    private void bt_stopWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stopWordsActionPerformed
        
        new StopWords();
    }//GEN-LAST:event_bt_stopWordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_gaps;
    private javax.swing.JButton bt_CleanFields;
    private javax.swing.JButton bt_Clipboard;
    private javax.swing.JButton bt_MakeGaps;
    private javax.swing.JButton bt_stopWords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rb_few;
    private javax.swing.JRadioButton rb_many;
    private javax.swing.JRadioButton rb_medium;
    private javax.swing.JTextArea ta_IN;
    private javax.swing.JTextArea ta_OUT;
    // End of variables declaration//GEN-END:variables
}
